In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv('supermarket_sales - Sheet1.csv')

In [3]:
ds

Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428      A     Yangon        Member  Female   
1    226-31-3081      C  Naypyitaw        Normal  Female   
2    631-41-3108      A     Yangon        Normal    Male   
3    123-19-1176      A     Yangon        Member    Male   
4    373-73-7910      A     Yangon        Normal    Male   
..           ...    ...        ...           ...     ...   
995  233-67-5758      C  Naypyitaw        Normal    Male   
996  303-96-2227      B   Mandalay        Normal  Female   
997  727-02-1313      A     Yangon        Member    Male   
998  347-56-2442      A     Yangon        Normal    Male   
999  849-09-3807      A     Yangon        Member  Female   

               Product line  Unit price  Quantity   Tax 5%      Total  \
0         Health and beauty       74.69         7  26.1415   548.9715   
1    Electronic accessories       15.28         5   3.8200    80.2200   
2        Home and lifestyle       46.33         7  16.2155   340.5255   
3         Health and beauty       58.22         8  23.2880   489.0480   
4         Sports and travel       86.31         7  30.2085   634.3785   
..                      ...         ...       ...      ...        ...   
995       Health and beauty       40.35         1   2.0175    42.3675   
996      Home and lifestyle       97.38        10  48.6900  1022.4900   
997      Food and beverages       31.84         1   1.5920    33.4320   
998      Home and lifestyle       65.82         1   3.2910    69.1110   
999     Fashion accessories       88.34         7  30.9190   649.2990   

          Date   Time      Payment    cogs  gross margin percentage  \
0     1/5/2019  13:08      Ewallet  522.83                 4.761905   
1     3/8/2019  10:29         Cash   76.40                 4.761905   
2     3/3/2019  13:23  Credit card  324.31                 4.761905   
3    1/27/2019  20:33      Ewallet  465.76                 4.761905   
4     2/8/2019  10:37      Ewallet  604.17                 4.761905   
..         ...    ...          ...     ...                      ...   
995  1/29/2019  13:46      Ewallet   40.35                 4.761905   
996   3/2/2019  17:16      Ewallet  973.80                 4.761905   
997   2/9/2019  13:22         Cash   31.84                 4.761905   
998  2/22/2019  15:33         Cash   65.82                 4.761905   
999  2/18/2019  13:28         Cash  618.38                 4.761905   

     gross income  Rating  
0         26.1415     9.1  
1          3.8200     9.6  
2         16.2155     7.4  
3         23.2880     8.4  
4         30.2085     5.3  
..            ...     ...  
995        2.0175     6.2  
996       48.6900     4.4  
997        1.5920     7.7  
998        3.2910     4.1  
999       30.9190     6.6  

[1000 rows x 17 columns]

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Invoice ID               1000 non-null   object 
 1   Branch                   1000 non-null   object 
 2   City                     1000 non-null   object 
 3   Customer type            1000 non-null   object 
 4   Gender                   1000 non-null   object 
 5   Product line             1000 non-null   object 
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64  
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object 
 11  Time                     1000 non-null   object 
 12  Payment                  1000 non-null   object 
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  

In [5]:
ds.describe()

Unit price     Quantity       Tax 5%        Total        cogs  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000   
mean     55.672130     5.510000    15.379369   322.966749   307.58738   
std      26.494628     2.923431    11.708825   245.885335   234.17651   
min      10.080000     1.000000     0.508500    10.678500    10.17000   
25%      32.875000     3.000000     5.924875   124.422375   118.49750   
50%      55.230000     5.000000    12.088000   253.848000   241.76000   
75%      77.935000     8.000000    22.445250   471.350250   448.90500   
max      99.960000    10.000000    49.650000  1042.650000   993.00000   

       gross margin percentage  gross income      Rating  
count              1000.000000   1000.000000  1000.00000  
mean                  4.761905     15.379369     6.97270  
std                   0.000000     11.708825     1.71858  
min                   4.761905      0.508500     4.00000  
25%                   4.761905      5.924875     5.50000  
50%                   4.761905     12.088000     7.00000  
75%                   4.761905     22.445250     8.50000  
max                   4.761905     49.650000    10.00000

In [6]:
ds.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [7]:
ds.duplicated().sum()

0

In [8]:
x_raw=ds[['Unit price','Quantity','Tax 5%','Total','cogs','gross margin percentage','gross income']].values

In [9]:
x_raw.shape

(1000, 7)

In [10]:
y_raw=ds[['Rating']].values

In [11]:
y_raw.shape

(1000, 1)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
prepro=StandardScaler()

In [14]:
x=prepro.fit_transform(x_raw)

In [15]:
x.shape

(1000, 7)

In [16]:
y=y_raw.astype(int)

In [17]:
y

array([[ 9],
       [ 9],
       [ 7],
       [ 8],
       [ 5],
       [ 4],
       [ 5],
       [ 8],
       [ 7],
       [ 5],
       [ 4],
       [ 6],
       [ 7],
       [ 8],
       [ 5],
       [ 4],
       [ 4],
       [ 6],
       [ 8],
       [ 4],
       [ 4],
       [ 5],
       [ 4],
       [ 9],
       [ 6],
       [ 8],
       [ 6],
       [ 7],
       [ 9],
       [ 7],
       [ 4],
       [ 4],
       [ 5],
       [ 5],
       [ 7],
       [ 6],
       [ 7],
       [ 4],
       [ 7],
       [ 7],
       [ 7],
       [ 6],
       [ 5],
       [ 7],
       [ 7],
       [ 9],
       [ 8],
       [ 4],
       [ 8],
       [ 7],
       [ 9],
       [ 8],
       [ 6],
       [ 6],
       [ 6],
       [ 8],
       [ 5],
       [ 6],
       [ 5],
       [ 9],
       [10],
       [ 7],
       [10],
       [ 8],
       [ 7],
       [ 5],
       [ 6],
       [ 9],
       [ 6],
       [ 4],
       [ 9],
       [ 5],
       [ 4],
       [ 8],
       [ 9],
       [ 5],
       [ 8],

In [18]:
y.shape

(1000, 1)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [21]:
x_train.shape,y_train.shape

((700, 7), (700, 1))

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
model=RandomForestClassifier()

In [24]:
model.fit(x_train,y_train)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11804\1002171229.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train,y_train)


RandomForestClassifier()

In [25]:
y_pred=model.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
print(confusion_matrix(y_test,y_pred))

[[ 9  5  7  5  4  7]
 [12 10  4 10  9 10]
 [11  7 14  6  6 15]
 [ 2  6 15  7  8 13]
 [10 11  6  8 11  8]
 [ 9  5  5  7 11  7]]
