In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
x= df.iloc[:, [2,3]].values

In [5]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [6]:
y=df.iloc[:, 4].values

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc=StandardScaler()

In [12]:
x_train_trans=sc.fit_transform(x_train)

In [13]:
x_test_trans=sc.fit_transform(x_test)

In [14]:
x_train_trans,x_train_trans.shape

(array([[-1.38691005, -0.04610893],
        [-0.44769331, -1.16152931],
        [ 0.86721012, -0.60381912],
        [ 1.05505347, -1.16152931],
        [-1.10514503, -1.48441416],
        [ 0.77328845,  1.45090263],
        [-1.76259675,  0.07130374],
        [-0.44769331,  1.33348996],
        [ 0.30368008,  0.33548225],
        [ 0.20975841, -0.31028745],
        [ 0.77328845,  0.33548225],
        [ 0.20975841, -0.25158111],
        [ 0.39760175, -0.39834695],
        [-0.25984996, -0.86799763],
        [-0.72945833,  0.57030759],
        [ 0.11583673,  1.12801778],
        [-0.35377164, -0.7212318 ],
        [ 0.39760175,  0.33548225],
        [-0.54161499,  1.53896213],
        [-0.25984996, -1.39635466],
        [-1.10514503,  0.54095442],
        [-0.25984996, -0.19287477],
        [ 0.86721012, -0.54511279],
        [-1.66867508, -0.92670397],
        [-1.1990667 ,  0.33548225],
        [-0.54161499,  2.41955717],
        [ 2.08819189, -0.63317229],
        [-1.10514503, -1.513

In [15]:
x_test_trans.shape

(160, 2)

In [16]:
y_train.shape

(240,)

In [17]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,SimpleRNN
from keras.losses import MeanSquaredError
from keras.optimizers import Adam

In [18]:
model=Sequential()
model.add(SimpleRNN(4,input_shape=(None,1),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 4)                 24        
                                                                 
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 145
Trainable params: 145
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(loss=MeanSquaredError(),optimizer=Adam(),metrics=['accuracy'])

In [20]:
model.fit(x_train_trans,y_train,batch_size=55,epochs=5)

Epoch 1/5
5/5 [==============================] - 2s 7ms/step - loss: 0.6417 - accuracy: 0.3583
Epoch 2/5
5/5 [==============================] - 0s 7ms/step - loss: 0.6417 - accuracy: 0.3583
Epoch 3/5
5/5 [==============================] - 0s 6ms/step - loss: 0.6417 - accuracy: 0.3583
Epoch 4/5
5/5 [==============================] - 0s 7ms/step - loss: 0.6417 - accuracy: 0.3583
Epoch 5/5
5/5 [==============================] - 0s 7ms/step - loss: 0.6417 - accuracy: 0.3583


In [21]:
model.evaluate(x_test_trans,y_test,batch_size=55)

3/3 [==============================] - 0s 4ms/step - loss: 0.6438 - accuracy: 0.3562


[0.643750011920929, 0.35624998807907104]